export const shortcuts = {
    "projects":"/projects",
    "media":"/media",
    "more":"/more",
    "home":"/",
    "us":"/us",
    "settings":"/settings",
    "users":"/users",
    "verify":"/verify",
    "blocked":"/blocked",
    "about":"/about",
    "admin": "/admin",
    "email":"/email",
    "username":"/username",
    "moderator":"/moderator",
    "change" : "/change",
    "change-password":"/change-password",
    "contact":"/contact",
    "offers":"/offers",
    "privacy":"/privacy",
    "terms":"/terms",
    "voting":"/voting",
    "pnf": "/not-found",
    "reviews":"/reviews",
    "login":"/login",
    "register":"/register",
    "forgot":"/forgot",
    "password":"/password",
}as const;

export const shortcutsMedia = {
    "yt":"https://www.youtube.com/@tarnovtv",
    "tiktok":"https://www.tiktok.com/@tarnovtv",
    "instagram":"https://www.instagram.com/tarnow_tv/",
} as const;
